#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Client
// 4.26.2-166672212+++UE4+Release-4.26

// 精简版SDK - 只包含必要的文件

#include "SDK/Basic.hpp"
#include "SDK/CoreUObject_structs.hpp"
#include "SDK/CoreUObject_classes.hpp"
#include "SDK/CoreUObject_parameters.hpp"
#include "SDK/Chaos_structs.hpp"
#include "SDK/PhysicsCore_structs.hpp"
#include "SDK/PhysicsCore_classes.hpp"
#include "SDK/InputCore_structs.hpp"
#include "SDK/SlateCore_structs.hpp"
#include "SDK/Slate_structs.hpp"
#include "SDK/Engine_structs.hpp"
#include "SDK/Engine_classes.hpp"
#include "SDK/Engine_parameters.hpp"
#include "SDK/AudioPlatformConfiguration_structs.hpp"
#include "SDK/PropertyAccess_structs.hpp"
#include "SDK/DeveloperSettings_classes.hpp"
#include "SDK/PacketHandler_classes.hpp"
#include "SDK/LGUI_structs.hpp"
#include "SDK/LGUI_classes.hpp"
#include "SDK/LGUI_parameters.hpp"
